import type { Catalog } from './catalog';
import { REPO_LABELS } from '../../core/src/classify';
import { kindLabels } from './github';
export const safeJson = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
export function renderCatalogHtml(catalog: Catalog): string {
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>我的 GitHub 工具箱 · Jev</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f5f0;color:#203d36;font:14px -apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',sans-serif}main{max-width:1200px;margin:auto;padding:56px 28px}.eyebrow{font-size:11px;letter-spacing:2px;color:#608475}h1{font-size:42px;letter-spacing:-2px;margin:16px 0}p{line-height:1.7;color:#708076}.tools{display:flex;gap:10px;flex-wrap:wrap;margin:30px 0 18px}input,select{padding:12px;background:#fff;border:1px solid #d9e2d6;border-radius:8px;color:#274e40;font:inherit}input{flex:1;min-width:220px}#grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:16px}.card{padding:24px;background:#fffefa;border:1px solid #dfe5d8;border-radius:14px;display:flex;flex-direction:column;gap:12px}.card a{font-size:16px;font-weight:650;color:#1d604b;text-decoration:none;overflow-wrap:anywhere}.card p{margin:0;flex:1;font-size:13px}.tags{font-size:11px;color:#627866}.note{padding:10px;border-radius:6px;background:#f1f5e9}#count{font-size:12px;margin-bottom:18px}.banner{border-left:3px solid #93b780;padding:10px 14px;background:#edf2e5}label{display:flex;align-items:center;gap:5px;font-size:12px}label input{min-width:0}footer{margin-top:40px;font-size:11px;color:#7e8f80}a:focus-visible{outline:3px solid #7cab90;outline-offset:4px}
</style><main><div class="eyebrow">JEV / STAR ATLAS</div><h1>收藏，有了秩序。</h1><p>一个可以随时找到好工具的地方。支持离线搜索与筛选。</p><div id="banner" class="banner"></div><div class="tools"><input id="search" type="search" placeholder="搜索工具、简介、主题或备注" aria-label="搜索工具"><select id="category" aria-label="用途分类"><option value="">全部分类</option></select><select id="kind" aria-label="工具形态"><option value="">全部形态</option></select><select id="language" aria-label="编程语言"><option value="">全部语言</option></select><select id="sort" aria-label="排序"><option value="stars">最多 Star</option><option value="name">名称</option></select><label><input id="archived" type="checkbox">隐藏已归档</label></div><div id="count" role="status"></div><div id="grid"></div><footer>本文件不连接网络、不加载远程资源。点击仓库链接时才会前往 GitHub。</footer></main><script>
const data=${safeJson(catalog)}, labels=${safeJson(REPO_LABELS)}, kinds=${safeJson(kindLabels)};
const el=id=>document.getElementById(id);const add=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
Object.entries(labels).forEach(([k,v])=>{const n=add('option',v);n.value=k;el('category').append(n)});Object.entries(kinds).forEach(([k,v])=>{const n=add('option',v);n.value=k;el('kind').append(n)});[...new Set(data.repositories.map(r=>r.language).filter(Boolean))].sort().forEach(v=>{const n=add('option',v);n.value=v;el('language').append(n)});
el('banner').textContent=(data.demo?'演示目录 · 固定样例，未调用模型':'Jev 分类 · '+data.repositories.length+' 个公开仓库')+(data.limited?' · 已达到读取上限':'');
function render(){const q=el('search').value.toLowerCase();const rows=data.repositories.filter(r=>(!el('category').value||r.category===el('category').value)&&(!el('kind').value||r.kind===el('kind').value)&&(!el('language').value||r.language===el('language').value)&&(!el('archived').checked||!r.archived)&&[r.full_name,r.description,r.note||'',...r.topics].join(' ').toLowerCase().includes(q)).sort((a,b)=>el('sort').value==='name'?a.full_name.localeCompare(b.full_name):b.stargazers_count-a.stargazers_count);el('count').textContent=rows.length+' / '+data.repositories.length+' 个工具';el('grid').replaceChildren();for(const r of rows){const card=add('article','','card');const link=add('a',r.full_name);link.href='https://github.com/'+r.full_name;link.target='_blank';link.rel='noopener noreferrer';card.append(link,add('p',r.description||'暂无简介'),add('div',(labels[r.category]||'待确认')+' · '+(kinds[r.kind]||'待确认'),'tags'),add('div','★ '+r.stargazers_count.toLocaleString()+' · '+(r.language||'—')+(r.archived?' · 已归档':'')+(r.manual?' · 人工确认':r.review?' · 待确认':''),'tags'));if(r.note)card.append(add('div',r.note,'note'));el('grid').append(card)}if(!rows.length)el('grid').append(add('p','没有匹配的工具，试试调整关键词或筛选条件。'));}['search','category','kind','language','sort','archived'].forEach(id=>el(id).addEventListener('input',render));render();
</script></html>`;
}
